import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// design-tokens.jsonを読み込み
const tokensPath = resolve(__dirname, '../core/design-tokens.json');
const tokens = JSON.parse(readFileSync(tokensPath, 'utf-8'));

// SCSSファイルを生成
function generateScss(tokens) {
  let scss = '// Auto-generated from design-tokens.json\n';
  scss += '// Do not edit this file directly\n\n';

  // Colors
  scss += '// Colors\n';
  Object.entries(tokens.colors).forEach(([key, value]) => {
    if (typeof value === 'object') {
      Object.entries(value).forEach(([shade, color]) => {
        scss += `$color-${key}-${shade}: ${color};\n`;
      });
    } else {
      scss += `$color-${key}: ${value};\n`;
    }
  });

  scss += '\n';

  // Spacing
  scss += '// Spacing\n';
  Object.entries(tokens.spacing).forEach(([key, value]) => {
    scss += `$spacing-${key}: ${value};\n`;
  });

  scss += '\n';

  // Breakpoints
  scss += '// Breakpoints\n';
  Object.entries(tokens.breakpoints).forEach(([key, value]) => {
    scss += `$breakpoint-${key}: ${value};\n`;
  });

  scss += '\n';

  // Font Size
  scss += '// Font Size\n';
  Object.entries(tokens.fontSize).forEach(([key, value]) => {
    scss += `$font-size-${key}: ${value};\n`;
  });

  scss += '\n';

  // Font Weight
  scss += '// Font Weight\n';
  Object.entries(tokens.fontWeight).forEach(([key, value]) => {
    scss += `$font-weight-${key}: ${value};\n`;
  });

  scss += '\n';

  // Border Radius
  scss += '// Border Radius\n';
  Object.entries(tokens.borderRadius).forEach(([key, value]) => {
    scss += `$border-radius-${key}: ${value};\n`;
  });

  scss += '\n';

  // Shadow
  scss += '// Shadow\n';
  Object.entries(tokens.shadow).forEach(([key, value]) => {
    scss += `$shadow-${key}: ${value};\n`;
  });

  return scss;
}

// SCSSファイルを保存
const scssOutput = generateScss(tokens);
const scssPath = resolve(__dirname, '../core/scss/abstracts/_tokens.scss');
writeFileSync(scssPath, scssOutput, 'utf-8');

console.log('✅ Design tokens generated successfully!');
console.log(`   Output: ${scssPath}`);
